apiVersion: v1
kind: Service
metadata:
  labels:
    app: tour-of-heroes-web
  name: tour-of-heroes-web
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 80
    targetPort: 5002
  selector:
    app: tour-of-heroes-web